services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=base_service
      - DB_SSLMODE=disable
      - FILL_INITIAL_DATA=true
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./migrations:/app/migrations
      - ./scripts:/app/scripts

  postgres:
    image: postgres:12
    container_name: postgresW
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=base_service
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
      - ./scripts:/docker-entrypoint-initdb.d/scripts
    restart: unless-stopped

volumes:
  postgres_data: